prefix: "&8[&6AutoRegion&8] "
lore: "This is a RegionCreator. Use it wisely!"
itemName: "Creates a region of %RADIUS%x%RADIUS%!"
blockOnFirstJoin: true
block: DIAMOND_ORE
auto-update: true
messages:
  noPermission: "&cYou don't have enough permission to execute this command!"
  disableRequest: "&cDo you really want to disable this plugin? Type &a'/autoregion confirm'&c to confirm"
  noDisableRequest: "&cThere is no disable request to confirm!"
  disabled: "&cSuccessfully disabled AutoRegion v%VERSION%! You have to restart your server to enable it again!"
  updatesDisabled: "&6Successfully &cdisabled&6 automatic updates!"
  updatesAlreadyDisabled: "&cAutomatic updates are disabled already!"
  updatesEnabled: "&6Successfully &aenabled&6 automatic updates!"
  updatesAlreadyEnabled: "&cAutomatic updates are enabled already!"
  list: "&7The following blocks are currently registered as RegionCreators:"
  noValidNumber: "&cThe Number you speicified (%NUMBER%) isn't a valid number!"
  blockAdded: "&6Successfully added %BLOCK% with a radius of %RADIUS%!"
  blockAlreadyAdded: "&c%BLOCK% has been added before!"
  blockNotAdded: "&cThe block you tried to remove doesn't exist!"
  blockNotSpecified: "&c%BLOCK% is not part of the config!"
  blockRemoved: "&6Successfully removed %BLOCK% from the config!"
  blockDoesntExist: "&cThe block you specified (%BLOCK%) isn't a valid block! Check for any spelling mistakes!"
  regionCreated: |
                  &6Succesfully created Region!
                  Owner: %OWNER%
  regionIntersecting: "&cThe region you tried to create is intersecting with another region!"
  searchingPlayer: "&cSearching for player %PLAYER%..."
  playerFound: "&cPlayer found! Proceeding..."
  playerNotFound: "&cThe Player %PLAYER% can't be found! Try again!"
  playerInventoryFull: "&c%PLAYER%'s inventory is full!"
  playerBlockAdded: "&6Successfully added %BLOCK% to %PLAYER%'s inventory!"
  playerBlockReceived: "&6You received a %BLOCK% to create a region (%RADIUS%x%RADIUS%)"
  playerWelcomeMessage: "&6As a welcome to the server you received a RegionCreator to create a region of %RADIUS%x%RADIUS%"
  maxRegionsReached: "&cYou already reached the maximum regions (%REGIONS%) for your group (%GROUP%)!"
groups:
  default: 2
  VIP: 5
regions:
